name: Deploy

on:
  push:
    branchs: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurando .NET
        uses: actions/setup-dotnet@v3 
        with:
          dotnet-version: 8.0.x

      - name: Instalando .NET Wasm Tools
        run: dotnet workload install wasm-tools

      - name: Restaurando as Dependências
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Criando o Publish
        run: dotnet publish pagamentos-uniforme-etec.csproj -c:Release -o docs --nologo

      - name: Configurando Pages
        uses: actions/configure-pages@v4

      - name: Enviando arquivos
        uses: actions/upload-pages-artifact@v3
        with: 
          path: "docs/wwwroot"

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
